### ISSUE TITLE
Custom component does not work

### ISSUE THREAD

**Issue by swaftrade** [shamruk/hass-components-sha#1]
Hi!
I am using Home Assistant version 0.109.6 (hass.io in docker) in Raspberry Pi4 
 - entities in systems appeared
 - switches in the interface do not change the state of the relay, and after a few seconds return to the off state
- in the log of the developer panel: 
Level: ERROR
Logger: custom_components.kincony-sha
Source: custom_components/kincony-sha/__init__.py:141
Integration: Kincony Sha (documentation)
First occurred: 0:04:47 (1 occurrences)
Last logged: 0:04:47

cannot connect socket

Level: WARNING
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:538
Integration: Switch (documentation, issues)
First occurred: 0:05:01 (11 occurrences)
Last logged: 0:10:11

Updating kincony-sha switch took longer than the scheduled update interval 0:00:30

please help deal with the problem

Thank you!

**Comment by shamruk** [comment]
Have you configured a correct IP address of the device?

**Comment by swaftrade** [comment]
yes
I change to my ip adress

**Comment by swaftrade** [comment]
Hi!
I'm sorry to bother you again...
I can’t solve this problem without your help.
thanks in advance!

**Comment by shamruk** [comment]
Is your device in UDP mode? Where have you taken the IP address?
https://www.kincony.com/kc868-h32-relay-remote-controller-exe-user-manual.html

**Comment by shamruk** [comment]
This also could be helpful . By the way what device do u have?
http://www.kincony.com/download/KC868-H8W&H32W_Wifi_version-user-manual.pdf

**Comment by swaftrade** [comment]
> Is your device in UDP mode? Where have you taken the IP address?
> https://www.kincony.com/kc868-h32-relay-remote-controller-exe-user-manual.html

hi!
Yes, device in UDP.
Static IP. set up in the program VirCom5.28_en.exe
screenshot - https://www.dropbox.com/s/3myuy0jf74kkeoq/3.jpg?dl=0
I have KC868-H32 Wi-Fi

**Comment by swaftrade** [comment]
Hello!
The device must be in the TSP server mode.
Now everything works.
 And one more thing: SwitchDevice is deprecated. I changed the switch.py file to SwitchEntity
